### ISSUE TITLE
Not working with external urls

### ISSUE THREAD

**Issue by mamodev** [Namide/extract-colors#22]
I'm using firestore from firebase to store my images.

`extractColors(url, { crossOrigin: "anonymus" }).then(console.log);`

i'm using the command with the crossorigin option, but it's giving me this exception anyway:

Access to image at **URL** from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Namide** [comment]
There is a typo in the code, use "anonym**o**us" instead of "anonymus".

Moreover the mandatory use of the canvas to extract the colors also requires an authorization on the side of the image server.
For example image 1 allows the use in a canvas but not image 2:
1. https://loremflickr.com/320/240/5/?lock=5
2. https://image.jeuxvideo.com/medias/158684/1586843712-8783-capture-d-ecran.jpg

Does image 1 work in your case?
Did my comment help you?
