### ISSUE TITLE
Not working so well with Vite

### ISSUE THREAD

**Issue by metehus** [Namide/extract-colors#26]
Hello! I'm using this library on a ViteJS project, and i encontered two problems.

The first one said the library was missing the `canvas` module, even though i'm using this library on the browser, but installing the library solved the issue

The other problem is regarding external URLs. Even using the `crossOrigin: 'anonymous'` option, I still get a `SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.` problem, but when i handle the Image object myself with the cors option, i get it to work

[Here's a sample of this problem](https://stackblitz.com/edit/vitejs-vite-b1kdzx?file=main.js)

What i suppose is that Vite is importing the node version of the module.

(Also, the [typing definitions](https://www.npmjs.com/package/@types/extract-colors) are completly wrong, requiring a string where the parameter can be an Image, which led to problems while using Typescript)

**Comment by Namide** [comment]
Hello @metehus,

You're right, Vite load the esm module of `extract-colors`. But esm module was made for NodeJS context (backend). NodeJS need canvas dependency because it don't have DOM. NodeJs context don't need CORS (Cross-origin resource sharing).

I've fix that by removig the base esm module, please update `extract-colors` to the  `1.1.23` version. You can update your project with the following command:

```bash
npm r extract-colors; npm i extract-colors@"<2.0.0"
```

Don't forget to remove the `canvas` dependency:

```bash
npm r canvas
```

If you need to force the esm module, you can follow the new documentation:

```js
import extractColors from 'extract-colors/dist/extract-colors.browser.es.js'

const src = 'my-image.jpg'

extractColors(src)
  .then(console.log)
  .catch(console.error)
```

About the Typescript definition, you're right, it's wrong.
I've not created the Typescript package, I just submitted a pull request to the owner of this package: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63102

Furthermore I will work on full Typescript lib in future to support clean Typescript definitions.

I'm closing this issue, if your error persist, please reopen it.
