### ISSUE TITLE
Can not compile in React

### ISSUE THREAD

**Issue by meilleureVie** [Namide/extract-colors#46]
Module parse failed: Unexpected token (186:61)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   pixels = 64e3,
|   distance: distance2 = 0.22,
>   colorValidator = (_red, _green, _blue, _alpha) => (_alpha ?? 255) > 250,
|   hueDistance: hueDistance2 = 0.08333333333333333,
|   saturationDistance = 0.2,

here is my package.json
[package.json](https://github.com/user-attachments/files/15521356/package.json)

**Comment by Namide** [comment]
Hello @meilleureVie,

I've just tested with the minimal setup in React/Vite and everything seems to work.
Here is my test :
- https://github.com/Namide/extract-colors-react-test
- https://namide.github.io/extract-colors-react-test/

The error must come from the configuration of your project or from an interfering dependency with extract-colors.

I don't have enough elements to test with only the package.json.
Could you please reproduce the error with a lightweight project, and share it with me so that I can test it?

Thanks in advance

**Comment by meilleureVie** [comment]
i finally end up making it work by replacing in my package.json
this:

>   "browserslist": {
>     "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   }

by this :

>  "browserslist":  [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
thank you for your time

**Comment by Namide** [comment]
Thanks for your feedback @meilleureVie,

With your solution, I understand where the error is coming from. The two messages in your logs seem to be about :
- `??` https://caniuse.com/mdn-javascript_operators_nullish_coalescing
- ` hueDistance: hueDistance2 = 0.08333333333333333` https://caniuse.com/mdn-javascript_operators_destructuring_computed_property_names

One of your dependencies detects these features as too recent.

In my opinion, they're widespread enough to keep them as is in the lib.
But if I get other similar requests from the community, I'll transpile them into the bundle.

I'm glad you found the solution.
If you have any other issues, please don't hesitate to share them.

Thanks
