### ISSUE TITLE
Could not find a declaration file for module ...

### ISSUE THREAD

**Issue by hidaehyunlee** [Namide/extract-colors#5]
Hi. Thanks for making a nice package.

I am using Node.js/React and want to use `extractColors` on my web page. 

But there is a little problem like this : "Could not find a declaration file for module ..."

![image](https://user-images.githubusercontent.com/37580034/98950726-b59a8400-253c-11eb-94c4-9dccdb1e32ae.png)

I have tried such methods as `npm install --save  -D @types/extract-colors` and `const { extractColors } = require('extract-colors')` to solve this problem, but it still doesn't work.

What do you think I should do?

**Comment by Namide** [comment]
Hi @hidaehyunlee,

I think this errors are triggered because you use Typescript.
The import need types for the module `extract-colors`.
It cannot find types because `extract-colors` contain only Javascript.

I have found solutions for you. Can you try one of theses?
- Add the line `// @ts-ignore` before the line `import extractColors from 'extract-colors'`
- Add the line `declare module '*';` in a file of your project with a `.d.ts` extension
- Use `require` instead `import` like `const extractColors = require('extract-colors');`

Does it work better?

**Comment by hidaehyunlee** [comment]
I don't know why this errors are triggered because I don't use Typescript.

Anyway, when I added the line `// @ts-ignore` , it worked at first. However It doesn't work again now. 😭
I think I need to solve it in a different way. I'll share it when I know the solution. Thanks!
